import type { Metadata } from "next";
import ReduxProvider from "../components/ProviderRedux";
import SessionProviderFn from "../components/SessionProviderFn";
import './globals.css';
import NavBar from "../components/NavBar";

export const metadata: Metadata = {
  title: "Payee",
  description: "Generated by PayeeVerse",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <SessionProviderFn>
        <html lang="en">
          <body className="dark:bg-black dark:text-white overflow-y-hidden">
            <NavBar />
            {children}
          </body>
        </html>
      </SessionProviderFn>
    </ReduxProvider>
  );
}
